In [1]:
#introduction to numpy
#Numpy is an open source library that is used for scientific calculations

##Why numpy is better than lists?
#(1). List hetrogenous(different) data types and Numpy homogenous(same) data type
#(2). List take more memory as compared to Numpy
#(3). List take more time execution as compare to Numpy


In [2]:
import numpy as np

In [3]:
a=[1,45,90]
type(a)

list

In [4]:
b=np.array(a)
type(b)

numpy.ndarray

In [5]:
#How can we create a user defined array?


In [9]:
a=[]
size=int(input("Enter size"))
for i in range(size):
    val=int(input("enter value"))
    a.append(val)

#print(a)
b=np.array(a)
b

Enter size 2
enter value 12
enter value 34


array([12, 34])

In [8]:
type(b)

numpy.ndarray

In [10]:
#How can we check shape,size,dimention of an array

In [11]:
a=[[1,2,3,0],[4,5,6,7],[7,8,9,1]]
b=np.array(a)
b

array([[1, 2, 3, 0],
       [4, 5, 6, 7],
       [7, 8, 9, 1]])

In [12]:
print("Total shape=",b.shape)

Total shape= (3, 4)


In [13]:
print("Total Elements=",b.size)

Total Size= 12


In [14]:
print("Total Dimentions=",b.ndim)

Total Dimentions= 2


In [1]:
#Pre defined functions in numpy


In [2]:
#(1). zeros()......>it will return an array in which all the values will be o in 
#either one dimentional or multidimenstional

In [1]:
import numpy as np
a = np.zeros((3))
a

array([0., 0., 0.])