In [1]:
import numpy as ns

In [2]:
a=[1,2,6,9]
type(a)

list

In [5]:
b=ns.array(a)
type(b)

numpy.ndarray

In [6]:
#Reshaping the array

In [7]:
# n(rows)*n(cols)=n(total_Elements)

#total_elements=12
#1*12,12*1
#2*6,6*2
#3*4,4*3

In [8]:
a=ns.arange(1,21,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
a.reshape(4,3)
a

ValueError: cannot reshape array of size 20 into shape (4,3)

In [12]:
a.reshape(4,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [14]:
#Operations on Array

In [15]:
a=ns.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [16]:
a**3

array([ 1,  8, 27, 64])

In [17]:
a*2

array([2, 4, 6, 8])

In [20]:
a=ns.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [21]:
b=ns.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [22]:
a+b

array([[ 6,  8],
       [10, 12]])

In [23]:
a-b

array([[-4, -4],
       [-4, -4]])

In [24]:
a*b#not going to work 

array([[ 5, 12],
       [21, 32]])

In [25]:
#use this to multiply
a.dot(b)

array([[19, 22],
       [43, 50]])

In [26]:
a=ns.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a=a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
#total sum
ns.sum(a)

np.int64(45)

In [33]:
ns.sum(a,axis=0)#### column wise sum

array([12, 15, 18])

In [35]:
ns.sum(a,axis=1)####row wise sum

array([ 6, 15, 24])

In [36]:
#UNique()....>it will return unique elements of array and its indexing and total occurance

In [37]:
a=ns.array([1,2,2,2,2,2,2,2,2,1,3,4,5])
ns.unique(a)

array([1, 2, 3, 4, 5])

In [39]:
ns.unique(a,return_index=True)

(array([1, 2, 3, 4, 5]), array([ 0,  1, 10, 11, 12]))

In [43]:
ns.unique(a,return_index=True,return_counts=True)

(array([1, 2, 3, 4, 5]), array([ 0,  1, 10, 11, 12]), array([2, 8, 1, 1, 1]))

In [44]:
#linspace().....>it will create an array in which gap of values will be equal.

In [45]:
a=ns.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [46]:
#Hstack and vstack

In [48]:
a=ns.array([1,2,3,4])
b=ns.array([5,6,7,8])
c=ns.array([9,10,11,12])
ns.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
ns.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])