In [1]:
#(2). ones() ...> it will create an array in which all the values are 1
import numpy as np

In [2]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [3]:
#(3). eye()..>it will create an array in which diagnol positinaol
#elements will be 1 and rest will be 0

In [4]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
#(4)....> using this method, we can create an array in which we
#customize our diagnol positinal ele.
a=np.diag([1,4,56,80])
a

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0, 56,  0],
       [ 0,  0,  0, 80]])

In [6]:
#(5)...>random Module

In [7]:
#(a).... It will generate random numbers in a given range
#Syntex np.randdom.randint(min_val,max_val,total_num)

In [10]:
a=np.random.randint(1,10,3)
a

array([2, 5, 4], dtype=int32)

In [12]:
#(b) rand()....> it ill generate random numbers in range 0-1
a=np.random.rand(3,3,)
a

array([[0.45344675, 0.28927355, 0.47286996],
       [0.98582228, 0.65943957, 0.19174699],
       [0.42849489, 0.02565346, 0.11474828]])

In [13]:
#(c) seed()....> it will fix our random generated data

In [16]:
np.random.seed(30)
a=np.random.randint(1,10,3)
a

array([6, 6, 5], dtype=int32)

In [1]:
#(6)....> view vs copy
#view means modification in original data
#copy means modification in duplicate data

In [2]:
impa=np.array([1,2,3,4,5,6,7,8,9])
b=a[2:5]
b[:]=0
b

NameError: name 'np' is not defined