In [1]:
import numpy as np

In [2]:
#2
a=[]
size=int(input("Enter the size"))
for i in range(size):
    val=int(input("Enter the value"))
    a.append(val)

b=np.array(a)
b

Enter the size 4
Enter the value 1
Enter the value 2
Enter the value 3
Enter the value 4


array([1, 2, 3, 4])

In [14]:
#3
a=np.random.randint(1,5,10)
a

array([3, 1, 2, 1, 2, 3, 3, 4, 1, 1], dtype=int32)

In [16]:
#4
a=np.arange(10,21,1)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
#5
#2
a=[]
size=10
for i in range(size):
    a.append(5)

b=np.array(a)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [20]:
#6
a=np.arange(1,10,1)
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
#7
a=np.random.rand(3,3)
a

array([[0.62287641, 0.71050107, 0.41104806],
       [0.99269345, 0.6899044 , 0.9831482 ],
       [0.18903792, 0.88660878, 0.86819995]])

In [40]:
#8
a=np.arange(1,7,1)
a.reshape(2,3)
b=np.arange(7,13,1)
b.reshape(2,3)
np.hstack(a)+np.hstack(b)
np.vstack(a)+

array([ 8, 10, 12, 14, 16, 18])